# SubNav
menu:
  #关于我: /2014/aboutme/
  友链: /2014/friends/
subnav:
  github: "https://github.com/Youthink"
  weibo: "http://weibo.com/u/5263249441"
  #zhihu: "https://www.zhihu.com/people/hu-yang-11-57/"
  email: "mailto:hufy78@gmail.com"
  sf: "https://segmentfault.com/u/youthink"
  #youthol: "http://www.youthol.cn"
  rss: "/atom.xml"

description: 天马行空，爱生活，爱coding

# SEO
seo_keywords: hexo,个人博客,blog
seo_description: 某某的个人博客

favicon: /favicon.ico

#你的头像url
avatar: https://tva3.sinaimg.cn/crop.0.0.200.200.180/005Kc3C1jw8f2uep0hhkvj305k05k3yk.jpg

# 首页左侧边栏背景图片
# 可配置多个 随机挑选一张
leftBackground:
  - https://ws3.sinaimg.cn/large/006tKfTcly1fsulzlvofnj30af0k5jvu.jpg
  - https://ws2.sinaimg.cn/large/006tNbRwly1fwl2alhqibj31kw2dcu0y.jpg
  - https://ws1.sinaimg.cn/large/006tNbRwly1fwl2bclcirj31kw2czk7v.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2c765jej31kw2d1npe.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2dentnvj31kw2dc1l2.jpg
  - https://ws4.sinaimg.cn/large/006tNbRwly1fwl2dqawiej31kw2d8x6p.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2f7yp25j31kw3a97wh.jpg

# 展示更新时间
display_updated: true

# 文章页的关于转载链接
copyright_url: https://888.com/index.html

# 底部的备案信息等
copyright_date: 2013-2018
beian_info: 某某的博客 京ICP备xxxxxx号

# Online contact
daovoice: true
daovoice_app_id: 123456 #输入app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: awwssw1snsnsnn1ndndnndnd99j

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 8888a8888
gitalk_clientSecret: 8888886666666
gitalk_repo: ****.github.io
gitalk_owner: admin
gitalk_admin: admin
# 是否启用评论框的全屏遮罩效果
gitalk_distractionFreeMode: false

